config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :largecategories
  resources :companies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  # belongs_to: 子が紐づいている親を表す
  belongs_to :small_category, inverse_of: :companies
  attachment :company_image
end

app/models/large_category.rb
class LargeCategory < ApplicationRecord
  # has_many: 1:nの関係を表す
  has_many :small_categories, dependent: :destroy, inverse_of: :large_category
  # 親作成時に子供も作成できるようになる
  accepts_nested_attributes_for :small_categories

  def check(small_category_name, company_name)
  	# p small_categories
  	small_category = small_categories.find_by(small_category_name: small_category_name)
  	if small_category
  		small_category.companies.find_by(company_name: company_name)
  	end
  end

end

app/models/small_category.rb
class SmallCategory < ApplicationRecord
  # belongs_to: 子が紐づいている親を表す
  belongs_to :large_category, inverse_of: :small_categories
  # has_many: 1:nの関係を表す
  has_many :companies, dependent: :destroy, inverse_of: :small_category
  # 親作成時に子供も作成できるようになる
  accepts_nested_attributes_for :companies

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def new
  	# Viewへ渡すためのインスタンス変数に空のモデルオブジェクトを生成する。
    @company = Company.new
    @smallcategories = SmallCategory.all
    # @large_category = LargeCategory.new
  end

  def create
  	# ストロングパラメータを使用
  	company = Company.new(company_params)
  	# DBへ保存する
  	if company.save
  	# 一覧画面へリダイレクト
  	  redirect_to companies_path
    else
      render :new
    end
  end

  def index
    @largecategories = LargeCategory.all
    @smallcategories = SmallCategory.all
    @companies = Company.all
  end

# 投稿データのストロングパラメータ
private
  def company_params
    params.require(:company).permit(:company_name, :company_image, :small_category_id)
  end

end

app/controllers/largecategories_controller.rb
class LargecategoriesController < ApplicationController

  def index
    @largecategories = LargeCategory.all
    @smallcategories = SmallCategory.all
    @companies = Company.all
    # @large_categories = LargeCategory.all.includes(:small_categories)
    # @small_categories = SmallCategory.all.includes(:companies)
  end

  def new
  	# インスタンス作成
  	@large_category = LargeCategory.new
    small_category = @large_category.small_categories.build
    small_category.companies.build
  end

  def create
    # find_or_create_by：条件検索に一致しない場合のみ登録し、条件に合致する内容があれば取得する
  	@large_category = LargeCategory.find_or_create_by(large_category_name: params[:large_category][:large_category_name])
    # update_attributes：データベースの値を複数同時に更新するために利用する
    p params[:large_category][:small_categories_attributes]
    p params[:large_category][:small_categories_attributes]["0"]
    if @large_category.check(params[:large_category][:small_categories_attributes]["0"][:small_category_name],
      params[:large_category][:small_categories_attributes]["0"][:companies_attributes]["0"][:company_name]) == nil
    @large_category.update_attributes(large_category_params)
      if @large_category.save
        redirect_to companies_path
      else
        render :new
      end
    end
  end

  def find_or_create_by(attributes, &block)
    find_by(attributes) || create(attributes, &block)
  end

private
def large_category_params
  # formから送られてくるパラメータの取得（ストロングパラメーター）# 親子孫のデータの作成
  params.require(:large_category).permit(:large_category_name, small_categories_attributes:
    [
        :small_category_name, companies_attributes:
          [
              :company_name, :company_image]
    ]
  )
end

end

app/controllers/smallcategories_controller.rb
class SmallcategoriesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/largecategories_helper.rb
module LargecategoriesHelper
end

app/helpers/smallcategories_helper.rb
module SmallcategoriesHelper
end

app/views/companies/index.html.erb
<div class="row">
  <h1 class="map-title">バイトテック（Arebeit Tech）カオスマップ 2019</h1>
</div>

<div class="row">
  <div class="clearfix">
    <% @largecategories.each do |largecategory| %>
  	<div class="col-xs-6 largecategory-box clearfix">
  	  <div class="largecategory-name">
        <%= largecategory.large_category_name %>
      </div>
       <% @smallcategories.each do |smallcategory| %>
       <% if smallcategory.large_category_id == largecategory.id %>
        <div class="smallcategory-box">
  	      <div class="smallcategory-name">
            <%= smallcategory.small_category_name %>
          </div>
             <% @companies.each do |company| %>
             <% if company.small_category_id == smallcategory.id %>
      	        <div class="company-box">
                   <%= attachment_image_tag company, :company_image, alt: "", width: "250" %>
                 </div>
             <% end %>
             <% end %>
  	    </div>
       <% end %>
       <% end %>
  	</div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-6 top-right-box">
    <div class="largecategory-box clearfix">
      <div class="largecategory-name">管理</div>
        <div class="smallcategory-box">
          <div class="smallcategory-name">シフト・勤怠管理</div>
            <div class="company-box">
             <img src="/assets/img/AirSHIFT.png" alt="" width="250">
            </div>
            <div class="company-box">
             <img src="/assets/img/jobkan.jpg" alt="" width="250">
            </div>
        </div>
        <div class="smallcategory-box">
          <div class="smallcategory-name">コミュニケーション</div>
            <div class="company-box">
             <img src="/assets/img/LINEWORKSlogo.jpg" alt="" width="250">
            </div>
            <div class="company-box">
             <img src="/assets/img/logo_talknote.png" alt="" width="250">
            </div>
        </div>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<h1 class="form-title">カオスマップ投稿フォーム</h1>

<div class="post-form">
<h2 class="post-type">データを1つずつ投稿</h2>
<%= form_for @company do |f| %>

  <h3>企業名</h3>
  　<%= f.text_field :company_name %>
  <h3>ロゴイメージ</h3>
  	<%= f.attachment_field :company_image %>
  <h3>カテゴリ（小）</h3>
  	<%= f.collection_select(:small_category_id, @smallcategories, :id, :small_category_name) %>

  <%= f.submit "送信" %>
<% end %>

</div>

<p class="link-to-index"><%= link_to("企業一覧", companies_path) %></p>
<p class="link-to-index"><%= link_to("カテゴリ追加", companies_path) %></p>

app/views/largecategories/index.html.erb
<div class="row">
  <h1 class="map-title">バイトテック（Arebeit Tech）カオスマップ 2019</h1>
</div>

<div class="row">
  <div class="clearfix">
    <% @largecategories.each do |largecategory| %>
  	<div class="col-xs-6 largecategory-box clearfix">
  	  <div class="largecategory-name">
        <%= largecategory.large_category_name %>
      </div>
       <% @smallcategories.each do |smallcategory| %>
       <% if smallcategory.large_category_id == largecategory.id %>
        <div class="smallcategory-box">
  	      <div class="smallcategory-name">
            <%= smallcategory.small_category_name %>
          </div>
             <% @companies.each do |company| %>
             <% if company.small_category_id == smallcategory.id %>
      	        <div class="company-box">
                   <%= attachment_image_tag company, :company_image, alt: "", width: "250" %>
                 </div>
             <% end %>
             <% end %>
  	    </div>
       <% end %>
       <% end %>
  	</div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-6 top-right-box">
    <div class="largecategory-box clearfix">
      <div class="largecategory-name">管理</div>
        <div class="smallcategory-box">
          <div class="smallcategory-name">シフト・勤怠管理</div>
            <div class="company-box">
             <img src="/assets/img/AirSHIFT.png" alt="" width="250">
            </div>
            <div class="company-box">
             <img src="/assets/img/jobkan.jpg" alt="" width="250">
            </div>
        </div>
        <div class="smallcategory-box">
          <div class="smallcategory-name">コミュニケーション</div>
            <div class="company-box">
             <img src="/assets/img/LINEWORKSlogo.jpg" alt="" width="250">
            </div>
            <div class="company-box">
             <img src="/assets/img/logo_talknote.png" alt="" width="250">
            </div>
        </div>
    </div>
  </div>
</div>

<p class="link-to-new"><%= link_to("新規投稿", new_largecategory_path) %></p>

app/views/largecategories/new.html.erb
<h1 class="form-title">カオスマップ投稿フォーム</h1>

<h2 class="post-type">データを投稿</h2>
<!-- LargeCategoryモデル -->
<%= form_for @large_category, url: largecategories_path do |f| %>

 <p><%= f.label :large_category_name, "カテゴリ名（大）" %></p>
 <%= f.text_field :large_category_name, class: 'form_control' %>

<br>
<!-- ここからSmallCategoryモデル -->
<%= f.fields_for :small_categories do |d| %>
  <p><%= d.label :small_category_name, "カテゴリ名（小）" %></p>
  <%= d.text_field :small_category_name, class: 'form_control' %>

<br>
  <%= d.fields_for :companies do |m| %>
    <p><%= m.label :company_name, "サービス名" %></p>
    <%= m.text_field :company_name, class: 'form_control' %>

    <p><%= m.label :company_image, "ロゴイメージ" %></p>
    <%= m.attachment_field :company_image, class: 'form_control' %>
  <% end %>
<% end %>

  <p><%= f.submit "送信" %></p>
<% end %>

<p class="link-to-index"><%= link_to("投稿一覧", largecategories_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChaosmakerSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header>
      <div class="header-middle clearfix">
         <a href="#main-visual">
          <img class="header-img" src="">
         </a>
         <nav>
          <div class="menu-box">
            <span class="list-bar"></span>
            <span class="list-bar"></span>
            <span class="list-bar"></span>
          </div>
          <ul class="nav-list">
            <li class="nav-list-item">top</li>
            <li class="nav-list-item">new</li>
            <li class="nav-list-item">map</li>
            <li class="nav-list-item">company</li>
          </ul>
         </nav>
      </div>
     </header>

     <div class="body">
       <div class="container">

          <%= yield %>


       </div>
     </div>


    <footer>
      <p class="footer-text">© All rights recerved by Reimi Goto</p>
    </footer>
  </body>
</html>